### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by Madis0** [Doclic/NoEncryption#1]
I'd recommend renaming this plugin to "No Chat Signatures" or similar. No Encryption is quite misleading, considering that Minecraft server connections are indeed encrypted since 1.8 or so and this doesn't change that.

**Comment by ARipePotato** [comment]
stfu and quit nitpicking. its just a name ffs.

**Comment by Doclic** [comment]
Renaming a plugin is pretty hard, because every link would break.
I also understand how that might confuse people but I explain it in my readme, so I don't think it's that big of a deal.

**Comment by CheaterTim** [comment]
> every link would break.

github redirects to the new name when you rename a repo, meaning if you renamed this repo to `alltheencryption` for example opening github.com/Doclic/NoEncryption would just redirect you to the new one, and for spigotmc only that number after `noencryption.` matters meaning this link works just fine: https://www.spigotmc.org/resources/alltheencryption.102902/ I am not sure if you can rename a resource on spigotmc though since I never published any myself

**Comment by V1nc3ntWasTaken** [comment]
I can add a clarification into the `/plugins` screen
